### ISSUE TITLE
Scaffolding does not Work - COMException when calling EntityFrameworkCore.Jet.Data.ComObject.TryGetMember

### ISSUE THREAD

**Issue by LuckyGeorge1975** [CirrusRedOrg/EntityFrameworkCore.Jet#216]
I've just started a simple project to test if i can read an access db with EF and the Jet Provider. But the scaffolding leads to a COM Exception 0x800A0CB3.

**What i have done**
1. Downloaded the latest northwind.accdb
2. Opened the DB in Access and VS 2022 Server Explorer to ensure that i can read the file
3. Setup a simple project and a corresponding test project

**Project:**
```lang-xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Jet" Version="8.0.0-alpha.2" />
    <PackageReference Include="EntityFrameworkCore.Jet.Data" Version="8.0.0-alpha.2" />
    <PackageReference Include="EntityFrameworkCore.Jet.Odbc" Version="8.0.0-alpha.2" />
    <PackageReference Include="EntityFrameworkCore.Jet.OleDb" Version="8.0.0-alpha.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.OleDb" Version="8.0.0" />
  </ItemGroup>

</Project>
```

**DBContext:**
```lang-cs
public class JetTestContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseJet(@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=<PATH>\northwind.accdb;");
    }
}
```

**Test:**
```lang-cs
[Test]
public void JetConnection()
{
    using (JetTestContext context = new JetTestContext())
    {
        context.Database.OpenConnection();
        context.Database.CloseConnection();
        Assert.IsTrue(context.Database.CanConnect());
    }
}
```

The Unit Test is successful.

After that i tried to scaffold the DB Context:

```lang-ps
Scaffold-DbContext -Connection "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=<PATH>\northwind.accdb;" -Provider EntityFrameworkCore.Jet -OutputDir Models
```

This results in the Exception:
```lang-cs
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x800A0CB3): Das Objekt oder der Provider kann den angeforderten Vorgang nicht ausführen.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at EntityFrameworkCore.Jet.Data.ComObject.TryGetMember(GetMemberBinder binder, Object& result)
   at CallSite.Target(Closure, CallSite, Object)
   at EntityFrameworkCore.Jet.Data.AdoxSchema.GetColumns()
   at EntityFrameworkCore.Jet.Data.PreciseSchema.GetColumns()
   at EntityFrameworkCore.Jet.Data.JetStoreSchemaDefinition.JetInformationSchema.GetColumns(JetConnection connection)
   at EntityFrameworkCore.Jet.Data.JetStoreSchemaDefinition.JetInformationSchema.GetDbDataReaderFromSimpleStatement(JetCommand command)
   at EntityFrameworkCore.Jet.Data.JetStoreSchemaDefinition.JetInformationSchema.TryGetDataReaderFromInformationSchemaCommand(JetCommand command, DbDataReader& dataReader)
   at EntityFrameworkCore.Jet.Data.JetCommand.ExecuteDbDataReaderCore(CommandBehavior behavior)
   at EntityFrameworkCore.Jet.Data.JetCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at EntityFrameworkCore.Jet.Scaffolding.Internal.JetDatabaseModelFactory.GetColumns(DbConnection connection, IReadOnlyList`1 tables)
   at EntityFrameworkCore.Jet.Scaffolding.Internal.JetDatabaseModelFactory.GetTables(DbConnection connection, DatabaseModel databaseModel, Func`3 filter)
   at EntityFrameworkCore.Jet.Scaffolding.Internal.JetDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at EntityFrameworkCore.Jet.Scaffolding.Internal.JetDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I also installed the latest Access Driver Engine but the result is the same.

What am i doing wrong?

**Comment by ChrisJollyAU** [comment]
It all looks like it should work. Almost all the time COM Exception tend to be when it can't find the COM class that it needs to create. Generally either because it is not installed or its looking for x86 when you have x64 installed or vice versa.

This is the links for the 2016 installer used with the testing system.
x64 https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/AccessDatabaseEngine_X64.exe
x86 https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/AccessDatabaseEngine.exe

Have a go at both. You will soon know which one installs as it doesn't like having different bit architecture installed at the same time
Just tried on my pc.
1. Created a new Empty Web Application
2. Added in the correct references and made sure it compiled
3. Without doing anything else, in the package manager console, executed `Scaffold-DbContext -Connection "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=c:\dev\northwind.accdb;" -Provider EntityFrameworkCore.Jet -OutputDir Models`
4. It scaffolded without any errors

My project file is
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Jet" Version="8.0.0-alpha.2" />
    <PackageReference Include="EntityFrameworkCore.Jet.Data" Version="8.0.0-alpha.2" />
    <PackageReference Include="EntityFrameworkCore.Jet.Odbc" Version="8.0.0-alpha.2" />
    <PackageReference Include="EntityFrameworkCore.Jet.OleDb" Version="8.0.0-alpha.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.OleDb" Version="8.0.0" />
  </ItemGroup>
</Project>
```

For the record, my environment has the 2010 x86 engine and Office 365 for x64. Doing the whole suite of tests is a bit more stable in x86

**Comment by LuckyGeorge1975** [comment]
Yesterday i tried the following:

1. Installed a brand new Windows 11 Environment in Hyper-V (english)
2. Installed the x64 Access Database Driver 2016 (english)
3. Installed the .net 8.0 x64 SDK
4. Installed VS Code (english)
5. Copied the project and the database
6. Ensured the dotnet environment is x64 via "dotnet --info"
7. Scaffold

--> Same Exception

After that i created a new project in the Hyper-V Machine, compiled it and tried to scaffold

--> Same Exception

I thought, that maybe when using the default language (english) and a brand new machine it will work, but it does not. I'm afraid i have to build the models for the access db manually or try to get it work in a pure x86 environment. Hopefully this will work.

**Comment by ChrisJollyAU** [comment]
Odd. I'm going to try install a VM and give it a try.

I have an empty test project that I will link with a database. Are you willing to give it a test.

In your cli just run `dotnet ef dbcontext scaffold "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=database3.accdb;" EntityFrameworkCore.Jet --output-dir db4`

There is already a db4 folder from a test run. You can either delete it or change the output dir name

<img width="857" alt="image" src="https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/assets/18402102/b3fe3bab-2f27-4d32-8801-730972b9e0eb">

Another thing to try is in the project file to ensure the platform target is for x64
`<PlatformTarget>AnyCPU</PlatformTarget>` (this line)

**Comment by ChrisJollyAU** [comment]
Installed the Windows 11 dev environment from Hyper V. Came with .Net 8.0.1 x64.
Installed Access  Engine x64
Installed EF Core tools (`dotnet tool install --global dotnet-ef`)
Ran the scaffold script as mentioned in the previous comment.
It worked.
Attached is the test project you can try with.

[WebApplication1.zip](https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/files/14166543/WebApplication1.zip)

I'm starting to wonder if there is a difference with the Northwind database you are testing on. Can you link that so I can look at it?

**Comment by yepeekai** [comment]
Is there a workaround?  I am having this issue with a database.

Thanks

**Comment by yepeekai** [comment]
In my case, It failed for an external/linked table.  I am no expert about that, I don't know if it would make sense to simply ignore them...

**Comment by ChrisJollyAU** [comment]
@yepeekai Interesting. Don't think we actually have code that knows how to deal with linked tables. May have to have a look and try replicate

**Comment by yepeekai** [comment]
Some context, I received a copy of that access database so the linked table are obviously not working since I do not have the other database.

I deleted all linked tables since I did not need them.  I compact/repair and then I get the same error at the same place for table : MSysACEs

**Comment by ChrisJollyAU** [comment]
@yepeekai @LuckyGeorge1975 Just added a commit to fix the main issue with the `MSys` tables.

You can now optionally ignore the `MSys` tables. Using `dotnet ef scaffold` or `Scaffold-DbContext` doesn't allow any extra custom options to be passed in so that left doing it through the connection string.

If you add `IgnoreMSys=YES;` to the connection string e.g. `"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=northwind.accdb;IgnoreMsys=YES;"` it will set the option to ignore the `MSys` tables when scaffolding.

You can try this out by referencing the daily builds

@yepeekai Regarding the linked tables, skipping/ignoring them would only work if they were stand alone. If there was any other foreign key/reference to them you would run into issues
