### ISSUE TITLE
Method 'get_LockReleaseBehavior' in type does not have an implementation.

### ISSUE THREAD

**Issue by roughiain** [CirrusRedOrg/EntityFrameworkCore.Jet#272]
Running the following command generates the following error

`dotnet ef dbcontext scaffold "Provider=Microsoft.ACE.OLEDB.12.0;Data Source={Removed};" EntityFrameworkCore.Jet`

```
System.TypeLoadException: Method 'get_LockReleaseBehavior' in type 'EntityFrameworkCore.Jet.Migrations.Internal.JetHistoryRepository' from assembly 'EntityFrameworkCore.Jet, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.JetServiceCollectionExtensions.AddEntityFrameworkJet(IServiceCollection serviceCollection)
   at EntityFrameworkCore.Jet.Design.Internal.JetDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices(String provider, IServiceCollection services, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)   
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method 'get_LockReleaseBehavior' in type 'EntityFrameworkCore.Jet.Migrations.Internal.JetHistoryRepository' from assembly 'EntityFrameworkCore.Jet, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```

**Comment by ChrisJollyAU** [comment]
It sounds like you are using alpha 1 from nuget.

That was built against the preview 7 of upstream EF Core. While for the most part it should work, there was a major change between the upstream RC1 and RC2 related to the History Repository (the part that deals with the `__EFMigrationsHistory` table).

This is the part that it is looking for and not finding.

I do have that fixed in the current daily builds (see #265) so the next release to nuget will have it.

In the meantime, you can try follow the instructions and link to a daily build.

I will keep this open for now until there is a version available in nuget that has the above fix in it

**Comment by ChrisJollyAU** [comment]
@roughiain There is a beta release that should now be on nuget that is compatible

**Comment by roughiain** [comment]
@ChrisJollyAU will test and give feedback

**Comment by roughiain** [comment]
Works! thank you.
